In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[88, 48],
       [79, 81],
       [63, 22],
       [69, 19],
       [19, 45],
       [69, 31],
       [59, 26],
       [44, 38],
       [40, 46],
       [99, 97]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

/home/gebruiker/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[0.8625    , 0.37179487],
       [0.75      , 0.79487179],
       [0.55      , 0.03846154],
       [0.625     , 0.        ],
       [0.        , 0.33333333],
       [0.625     , 0.15384615],
       [0.5       , 0.08974359],
       [0.3125    , 0.24358974],
       [0.2625    , 0.34615385],
       [1.        , 1.        ]])

In [8]:
result = scaler_model.fit_transform(data)

/home/gebruiker/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
result

array([[0.8625    , 0.37179487],
       [0.75      , 0.79487179],
       [0.55      , 0.03846154],
       [0.625     , 0.        ],
       [0.        , 0.33333333],
       [0.625     , 0.15384615],
       [0.5       , 0.08974359],
       [0.3125    , 0.24358974],
       [0.2625    , 0.34615385],
       [1.        , 1.        ]])

In [10]:
import pandas as pd

In [11]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [12]:
data.head()

f1  f2  f3  label
0  79  53  87     68
1  50  64   6     25
2  44  85  70     93
3   6  51  14     10
4  47  50  91     11

In [14]:
x = data[['f1','f2','f3']]
y = data['label']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [17]:
X_train.shape

(35, 3)

In [18]:
X_test.shape

(15, 3)

In [19]:
y_train.shape

(35,)

In [20]:
y_test.shape

(15,)